# Personal DB (H2)
spring.datasource.personal.jdbc-url=jdbc:h2:file:./db/personal;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.personal.driver-class-name=org.h2.Driver
spring.datasource.personal.username=sa
spring.datasource.personal.password=

# Financial DB (H2)
spring.datasource.financial.jdbc-url=jdbc:h2:file:./db/financial;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.financial.driver-class-name=org.h2.Driver
spring.datasource.financial.username=sa
spring.datasource.financial.password=

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update