services:
  - type: web
    name: g1m-webrtc-server
    env: rust
    plan: free
    buildCommand: "cargo build --release --manifest-path g1m-node/Cargo.toml"
    startCommand: "./g1m-node/target/release/g1m-node"
    rootDir: ./