# サーバーポートの設定
server.port=8080

# SQLiteの設定 (g1m-nodeと共有するプロジェクトルートのDBを参照)
spring.datasource.url=jdbc:sqlite:g1m.db
spring.datasource.driverClassName=org.sqlite.JDBC
# SQLite用のDialect設定 (コミュニティ版やGenericを使用)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# 起動時にDBテーブルを自動作成
spring.jpa.hibernate.ddl-auto=update
# ログ設定 (SQLを表示)
spring.jpa.show-sql=true
