services:
  z1m-java-unit:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ../../g1m.db:/app/g1m.db
      - ../../z1m/AirWallet:/app/z1m/AirWallet
    environment:
      - SPRING_PROFILES_ACTIVE=dev
